### ISSUE TITLE
Anti-aliasing?

### ISSUE THREAD

**Issue by randytroppmann** [StarlingGraphics/Starling-Extension-Graphics#11]
What would be the best approach to anti-aliasing? Rotated rectangle look quite aliased.

**Comment by CrazyFlasher** [comment]
04_Fill_Stroke_Example works incorrect with Context3DProfile.BASELINE:

http://joxi.ru/lJ2beK7UoL6Xm6 - Context3DProfile.BASELINE - invalid
http://joxi.ru/1bmoo8pUQE49my - Context3DProfile.BASELINE_CONSTRAINED - ok
