### ISSUE TITLE
Graphics stop working after Context loss

### ISSUE THREAD

**Issue by ddoerr** [StarlingGraphics/Starling-Extension-Graphics#110]
I have a simple drawing screen in my app for iOS. 

![bildschirmfoto 2014-05-09 um 09 48 48](https://cloud.githubusercontent.com/assets/1156293/2925575/6771bf5c-d74e-11e3-8f9a-8411b8d80b51.png)

Works fine until i take a photo on another screen of my app, which leads to a lost context, then when i come back to the drawing it doesnt work at all. Touch event fires, but no lines are drawn. Any ideas? (iPad, AIR 13, iOS7, Starling 1.4.1, Feathers 1.2)

**Comment by vrabete** [comment]
Does anyone have a clue why Shape does not show anymore after I lose context because I lock out? No new Shape is showing anymore at all and I don't find onGraphicLostContext in Graphics extension (not even in the latest update)

**Comment by IonSwitz** [comment]
I have submitted a fix for this, or at least a problem related to Lost Context
