### ISSUE TITLE
Fatal error: The application lost the device context! when the phone rotate

### ISSUE THREAD

**Issue by pol2095** [StarlingGraphics/Starling-Extension-Graphics#123]
Hello,

I have a "Fatal error: The application lost the device context!" when my Android phone (Nexus 5) rotate

var shape:Shape = new Shape();
addChild(shape);
shape.graphics.beginFill(0xc72046);
shape.x = border.y = 20;
shape.graphics.lineStyle(4, 0xFFFFFF, 1);
shape.graphics.drawRect(0, 0, 150, 150);
shape.graphics.endFill();

Thanks

**Comment by IonSwitz** [comment]
A fix for this has been submitted
