### ISSUE TITLE
Two questions regarding quality

### ISSUE THREAD

**Issue by joeshields-at-gruden** [StarlingGraphics/Starling-Extension-Graphics#129]
Hi, I'm adding a rounded rect in my Air iOS app and the top left corner seems to have a slice of the corner slices missing, I have tried changing x,y,w,h,border radius and cannot get this last piece to work. All other corners are working as expected. Please see the image attached.

Is there a way to increase the number of corner radius pieces? thereby theoretically increasing the quality of the curve?

Cheers
![screen shot 2015-03-02 at 4 00 06 pm](https://cloud.githubusercontent.com/assets/3699138/6444485/c6c9495c-c0f5-11e4-91f0-db26f6d5a20f.png)

**Comment by IonSwitz** [comment]
I've checked in a fix, and I have tried it with a number of different test scenarios, but please let me know if you find something odd...

**Comment by joeshields-at-gruden** [comment]
Spot on, fixed. Thanks.
