### ISSUE TITLE
Shape width calculated incorrectly

### ISSUE THREAD

**Issue by BwackNinja** [StarlingGraphics/Starling-Extension-Graphics#130]
When drawing a line using a Shape, from (0, 20) to (10, 20) the width and height will both be 20. Typo on line 182 of extension/src/starling/display/graphics/Stroke.as.

"maxBounds.x = y;" should be "maxBounds.x = x;"

**Comment by IonSwitz** [comment]
Thank you - that was an embarrassing mistake.
