### ISSUE TITLE
Texture no repeat in TextureVertexColorFragmentShader

### ISSUE THREAD

**Issue by pSi-X** [StarlingGraphics/Starling-Extension-Graphics#140]
Hi, sory my bad English :)
I encountered a problem that can be seen in the [screenshot](http://joxi.ru/Vm6k9BdfaM3j2Z):
![Image of problem](http://dl1.joxi.net/drive/0008/2829/535309/150827/89ce39564b.jpg)
When I started to dig deeper, I found a bug in the class TextureVertexColorFragmentShader:
```
public function TextureVertexColorFragmentShader(texture:Texture = null, mipmapping:Boolean = false, repeat:Boolean = false, smoothing:String = "bilinear") {
   //Bad:
   var shouldRepeat:Boolean = texture == null ? repeat : ( texture.repeat ? repeat : false);
   //Good:
   var shouldRepeat:Boolean = texture == null ? repeat : texture.repeat;
   ...
}
```
It is a repeat of the texture will never be taken.
Please fix this bug.

Best regards, pSi-X

**Comment by IonSwitz** [comment]
Thanks for reporting this, but.. if you set "texture.repeat=true" and the variable "repeat = true" when you call the constructor of TextureVertexColorFragmentShader, "shouldRepeat" will become true, yes?

I agree it's not a pretty solution, but it should at least give the correct functionality, I think?

**Comment by pSi-X** [comment]
Maybe that variant is correct:
```
var shouldRepeat:Boolean = texture == null ? repeat : (texture.repeat || repeat);
```
But yes, this solution repairs situation with TextureMaterial and TextureVertexColorFragmentShader :)

**Comment by pSi-X** [comment]
Please close the issue and to commit with such a decision:
```
var shouldRepeat:Boolean = texture == null ? repeat : (texture.repeat || repeat);
```
Thank you! :)

**Comment by pSi-X** [comment]
Please close the issue and to commit with such a decision:
```
var shouldRepeat:Boolean = texture == null ? repeat : (texture.repeat || repeat);
```
Thank you! :)

**Comment by IonSwitz** [comment]
This is a poorly designed API. The correct way to use this would be to force the person calling the method to specify the "repeat" argument to true or false. This is a good example where an argument with a default value causes problems.

To be honest, I don't want to change the API since that might cause backwards compatability issues. What situation do you have where you can't get the correct values to be set?

If you need the "shouldRepeat" to be set to either true or false, you can currently make that happen by setting values in the constructor appropriately.

**Comment by pSi-X** [comment]
In the class TextureMaterial creates an instance of the class TextureVertexColorFragmentShader without repetition, and the default value ```false```, so the value shouldRepeat ```var shouldRepeat:Boolean = texture == null ? repeat : ( texture.repeat ? repeat : false)``` always is ```false```:
```
public function TextureMaterial(texture:Texture, color:uint = 0xFFFFFF, premultipliedAlpha:Boolean = true) {
    super(new StandardVertexShader(), new TextureVertexColorFragmentShader(texture));
    ...
}
```

**Comment by IonSwitz** [comment]
I have updated the TextureMaterial to take more arguments, that gets sent to the TextureVertexColorFragmentShader.

This should give you the flexibility you need without sacrificing backwards compatibility.

**Comment by pSi-X** [comment]
Thank you very much, now works as needed! ^_^

**Comment by pSi-X** [comment]
But now, an extra comma after ```texture,,```:
```
super(new StandardVertexShader(), new TextureVertexColorFragmentShader(texture,, mipmapping, repeat, smoothing ));
```
