### ISSUE TITLE
Duplicate variable definition of function paramters

### ISSUE THREAD

**Issue by 26letters** [StarlingGraphics/Starling-Extension-Graphics#142]
While using this extension with AIR 19 and FlashDevelop 5.0.1 I am having this compile time error. 
Its at the 'GraphicsEx' class at line number 302 & 372. The function names are 'postProcessThicknessColorInternal' & 'postProcessThicknessInternal'

The error statement is : Warning: variable definition duplicates function parameter: numVerts.

**Comment by IonSwitz** [comment]
Hi. Thanks for reporting this. I've submitted a code fix to the GraphicsEx class. Very embarrasing.

Please try out the new version (Remember, the SWC is not updated, only the source tree) and, if this fixes the problem, please close this issue.

**Comment by 26letters** [comment]
I am sorry but I am new to github and I am not sure if I am checking the right link where you have added the fix. I am checking here : https://github.com/StarlingGraphics/Starling-Extension-Graphics/blob/master/extension/src/starling/display/graphicsEx/GraphicsEx.as 

And I couldn't find any change in the code at the 2 functions.

**Comment by IonSwitz** [comment]
I am very sorry. The git skills I used to have was ruined by a year of using perforce at work. I forgot to sync up my commit. Now, the fix is in place. I apologize for that.

**Comment by 26letters** [comment]
Ok, its there now. One more thing I want to ask (though this is not the right place to ask) is about using the extension. I have added a thread at the starling forums but it would be great if you can help me with that. 

Currently I am replacing the 'starling' folder of my starling classes with the starling folder provided by your extension and trusting that the extension is not breaking the framework. Is that the right way ?? OR should I keep the two folders separate and it will work ?? Are you making any changes to the classes from the starling's display folder ??

**Comment by IonSwitz** [comment]
When I set up a project that is using Starling extensions, I place the extensions in different folders, and add one src paths to each extension.

For example, I can have the main Starling code in 

3rdParty/Starling/Starling

and the extensions in

3rdParth/Starling/Extensions

where each extension has its own directory:

3rdParth/Starling/Extensions/StarlingGraphicsExtension
3rdParth/Starling/Extensions/Lightning

or similar.

Then I add one source path to the Starling/Starling folder and one source path to each of the extension directories, like this:

![image](https://cloud.githubusercontent.com/assets/3709822/11822835/ec7269fa-a370-11e5-9f32-2c595b1833f1.png)
