### ISSUE TITLE
extra comma in TextureMaterial class

### ISSUE THREAD

**Issue by pSi-X** [StarlingGraphics/Starling-Extension-Graphics#143]
Now, an extra comma after ```texture,,``` in TextureMaterial class:
```
super(new StandardVertexShader(), new TextureVertexColorFragmentShader(texture,, mipmapping, repeat, smoothing ));
```

**Comment by IonSwitz** [comment]
Haha I dont understand this, I used the class before checking it in. Anyway, the code is updated. Very sorry for this typo
