### ISSUE TITLE
Context loss SEG not recovering - No valid program set.

### ISSUE THREAD

**Issue by Selonie** [StarlingGraphics/Starling-Extension-Graphics#147]
In my game I to am experiencing issues with textures not showing up when my device sleeps. I can reproduce this every time on the desktop with Ctr Alt Del.
This can be demonstrated in the provided GraphicsAPIExample. The issue only seems to occur when clear() is called, I'm guessing clear is getting called before the graphics have been restored.

To reproduce: Load up the GraphicsAPIExample, Ctr Alt Del, open task manager or cancel.

This doesn't happen when I roll back to a version from 2 June 2015.

[Fault] exception, information=Error: Error #3600: No valid program set.
flash.display3D::Context3D/drawTriangles
starling.display.materials::StandardMaterial/drawTrianglesEx at C:\Users\Selonie\Starling-Extension-Graphics-master\extension\src\starling\display\materials\StandardMaterial.as:149
starling.display.materials::StandardMaterial/drawTriangles at C:\Users\Selonie\Starling-Extension-Graphics-master\extension\src\starling\display\materials\StandardMaterial.as:123

**Comment by IonSwitz** [comment]
Thank you, I will investigate this ASAP. A clear reproduction always helps :)

**Comment by IonSwitz** [comment]
This is annoying. I can not repeat it, it works fine for me. 

I am running Windows 10, Starling starts with "DirectX11 Baseline Constrained", Flash Player 20, debug or release makes no difference.

However, if I resize the window, everything clears out.

**Comment by Selonie** [comment]
Thanks, for looking into this -  I was about to go through my tests again until I saw your edits!

**Comment by IonSwitz** [comment]
I think the fix works fine. Please get the latest sources and try again.

**Comment by Selonie** [comment]
That was quick! Just running a few tests on desktop and device - In my game and the demo both seem to be recovering normally where before they were misbehaving. Thanks.
