### ISSUE TITLE
starling.core.RenderSupport problem with Starling 2 

### ISSUE THREAD

**Issue by joy2play** [StarlingGraphics/Starling-Extension-Graphics#148]
Hi,
Below error is throwing while integrating starling 2.0 in my project 

**The definition starling.core.RenderSupport depended on by starling.display.graphics.Graphic in the SWC \lib\swc\Starling-Extension-Graphics.swc could not be found**

Please check and fix it ASAP.

Thanks.

**Comment by IonSwitz** [comment]
Please take a few minutes to read the issues that already exist before posting.

**Comment by joy2play** [comment]
let me know the issue link so i can follow it thanks

**Comment by IonSwitz** [comment]
I'd recommend you to check out the issue named "Starling 2.0" 

Since that issue is at the top of the issue list, and is titled "Starling 2.0", I thought it would be easy to find.

**Comment by joy2play** [comment]
Got it Thanks
