### ISSUE TITLE
[Feature Request] Get vertex positions from Stroke

### ISSUE THREAD

**Issue by AlBirdie** [StarlingGraphics/Starling-Extension-Graphics#73]
Just for clarification, I needed to draw a parallel Stroke to an existing one. In order to calculate the parallel Stroke's start and end points, it was required to get the the start and end points of the original Stroke.
For that I added this little function to the Stroke class;

public function getPointAtVertex(pos:int):Point {
    var _point:Point = new Point();
    _point.x = _line[pos].x;
    _point.y = _line[pos].y;
    return _point;
}

Please let me know what you think about this. I'm not sure if this would be of any benefit for others or if there is a better way to accomplish this. Looking forward to any feedback.

**Comment by IonSwitz** [comment]
Just adding a comment here, @AlBirdie , I have added a Stroke.evaluate() method, that allows you to get any point along any Stroke, from a "t" value that is between 0.0 and 1.0 of the line's total length. Not sure that you still need it, but it is pretty darn nifty. Check here:

http://forum.starling-framework.org/topic/starling-extension-graphics#post-83189
